name: Reusable workflow
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deploybanle artifact false
        required: true
        default: dist
        type: string
    #secrets:
      #some-secret:
        #required: false
    outputs:
      result:
        description: The resylt of all operation}
        value: ${{ jobs.deploy.outputs.general-output }}
jobs:
  deploy:
    outputs:
      general-output: ${{ steps.set-result-output.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output info
        run: echo "Deploying and uploading ..."
      - name: Set result output
        id: set-result-output
        run: echo "step-result=success" >> $GITHUB_OUTPUT